---
title: "Predicting Obesity Status"
author: "Cynthia Du"
date: "November 27, 2024"
---

Download the presentation [here](predictingobesity.pdf)

Download the report [here](obesity_report.pdf)

#### Project Overview

Obesity is a chronic disease that happens when an individual has an abnormally excessive amount of body fat. This disease poses significant risks for other life threatening illnesses such as hypertension, cardiovascular diseases, diabetes, cancer, and various musculoskeletal disorders. It is a major global health issue, especially in the US, with obesity rates steadily increasing over the past few decades. Early detection and prevention of obesity can mitigate these health risks and improve overall public health. However, in order to identify individuals at risk of obesity, we must analyze the interactions between demographic, lifestyle, and health-related factors.

Our project focused on exploring a dataset with lifestyle, demographic, and health-related attributes to leverage predictive modeling techniques to predict obesity. The training dataset includes 32,014 entries with variables such as age, gender, dietary habits, physical activity levels, biometric measurements, and obesity status. The testing dataset includes 10672 entries with all the same variables as the training dataset, except obesity status. Our report will detail how we built our classification model spanning from EDA to data cleaning to variable and model selection to a discussion of our results and limitations.

After investigating machine learning models such as logistic regression, decision trees, and random forests we evaluated the performance of these models and concluded that the random forest model was best. Ultimately we ended with a kaggle score of 0.997 and rank 15.

#### Models Used

**Logistic Regression**

Logistic regression is used for modeling the relationship between a binary dependent variable and one or more independent variables. This makes it particularly suitable for classification problems, such as predicting whether an individual is obese. One of its strengths is its simplicity and interpretability, as the coefficients provide insights into how each predictor affects the likelihood of the outcome.

**Linear Discriminant Analysis - LDA**

Linear Discriminant Analysis is a classification algorithm that performs dimensionality reduction while maximizing class separability. In this project, we used LDA with 10-fold cross-validation to predict obesity based on the following selected features: "Cholesterol", "CH2O", "FCVC", "family_history_with_overweight", "CAEC", and "FAVC". The 10-fold cross-validation was used to evaluate the models performance and ensure stronger results.

**Random Forest**

Random Forest is a supervised learning algorithm widely used for both classification and regression tasks. It operates by constructing multiple decision trees during training and aggregating their predictions to produce a final result, typically based on majority voting or averaging. We chose the Random Forest model for its accuracy and efficiency. To refine it, we identified the top ten predictors, including height, race, age, physical activity frequency (FAF), caloric intake (CALC), and the number of meals per day (NCP), using feature importance metrics and visual analysis.

#### Conclusion

Overall, our model achieved a high accuracy of 0.997 in predicting obesity status, demonstrating the effectiveness of the Random Forest model in this context. However, we acknowledge some limitations in our approach that may have impacted the model's performance. For example, during data cleaning, missing values were imputed using median and mode imputation, which assumes that the underlying data distributions are normal. While this method allowed us to handle missing data efficiently, it may have introduced biases or affected the predictive power of certain variables. Additionally, our assumptions about how the observations were gathered and the relationships between predictors could limit the model’s generalizability to different populations or datasets.
