project:
  type: website

website:
  title: "Cynthia Du"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
      - href: clubexperience.qmd
        text: Club Experience

format:
  html:
    theme: 
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  