---
title: "About"
toc: true
---

## Work Experience

#### Workday \| Data Science Intern \| June 2025 - present

• Designed a Tableau dashboard for the President of Product & Technology and 20+ PMs to track task coverage across thousands of software tasks. Integrated 1B+ records from three SQL sources to flag tracked, untracked, and high-priority tasks based on user activity and transactions, enabling targeted improvements to increase software coverage

•	Automated multi-API data extraction in Python, pulling 100K+ JSON records and cutting manual effort by 90%, then reformatting and integrating data into existing datasets to expand model training data by 3x

•	Built logistic regression (with WoE binning) and XGBoost (with PCA) models to predict website findability, performing extensive feature engineering and target variable testing to boost accuracy by 25% and inform UX improvements


#### TraceGains \| Data and AI Associate \| October 2024 - present

• Created an AI-powered system that improves customer modules by identifying risks in real time and generating user alerts

• Designed interactive risk cards that incorporate urgency markers and facilitate user-friendly access to complex data

• Collaborated closely with product and engineering teams to implement a large language model (LLM) application to provide comprehensive overviews of daily alerts and assess supply chain sustainability metrics, enhancing strategic decision-making

#### TraceGains \| Data Analyst Intern \| June 2024 - September 2024

• Improved supplier location and item mapping accuracy by 60% on 80k+ supplier data with 550k+ ingredients using NLP, PyTorch, and MiniLM BERT models, thus reducing manual data sorting time by 85%

• Optimized supplier data processing, achieving a 262% increase in high-quality matches and a 99% reduction in NULL matches, and developed 2000+ new categories to enhance operational metric tracking

#### IBM \| IBM Accelerate Client Engineering + Technical Sales \| May 2024 - July 2024

• Designed, implemented, and tailored online chatbot for IBM client using NLP, LLM, and sentiment analysis to summarize conversations, collect sentiment, and provide information, increasing business efficiency and customer satisfaction

• Led demonstration of Watsonx generative AI chatbot, utilizing engaging conversation, active listening, critical thinking, and persuasive communication to effectively showcase its advantages, aligning with the company's goals

#### UCLA Teaching and Learning Lab \| Undergraduate Research Assistant \| Sept 2023 - June 2024

•	Cleaned and transformed large-scale high school textbook usage data and 500K+ student survey responses from an online learning platform, performing statistical correlation to link engagement metrics and motivation with learning outcomes

•	Built a recommendation system for personalized study focus areas and created visualizations to identify underperforming content, driving targeted updates to 3 of 10 chapters and improving comprehension scores


## UCLA Work Experience

#### UCLA Residential Life \| Lead Resident Assistant \| September 2024 - present

• Assist new RA's in navigating the role and responding to conflicts and medical emergencies

• Organize team bonding activities to better communication within the team and foster a supportive environment where RAs can rely on each other 

#### UCLA Residential Life \| Resident Assistant \| September 2023 - present

• Support a floor of 90 residents academically, socially, and emotionally through active and passive programming, active listening, conflict mediation, and referrals to appropriate resources

• Provide a safe environment for students by responding to incidents and medical emergencies, and documenting reports to address resident needs and concerns promptly and effectively
